// Generated by CoffeeScript 1.7.1

/*
 * 配置文件
 */

(function() {
  var WEB_URL_ROOT, loadWebUrlRoot;

  WEB_URL_ROOT = "http://gamagama.cn";

  loadWebUrlRoot = function() {
    return WEB_URL_ROOT;
  };

}).call(this);
