// Generated by CoffeeScript 1.7.1
var config, enterProject, signUtil;

config = require("./config");

signUtil = require("./sign_util");

enterProject = function() {
  var id, serial, signData, uri;
  id = $("#project_id").val().trim();
  serial = $("#serial").val().trim();
  uri = "" + (config.loadWebUrlRoot()) + "/projects/" + id;
  signData = signUtil.sign("GET", uri, id, serial);
  return $.ajax(uri, {
    type: 'GET',
    dataType: 'json',
    data: signData,
    success: function(result) {
      if (result.success) {
        config.setProjectSerial(serial);
        config.setProjectId(result.data.id);
        config.setProjectName(result.data.name);
        return window.location.href = "./asset.html";
      } else {
        return bootbox.alert(result.msg);
      }
    },
    error: function(jqXHR, textStatus, err) {
      return bootbox.alert("error:(" + textStatus + "): " + err);
    }
  });
};
